# Generated by Django 4.2.5 on 2023-09-14 14:36

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('JanataWifi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='volume',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
